In [31]:
import numpy as np
import math
income = np.random.randint(10000,100000,1000000)
print(income)
print(np.average(income))

[44629 82881 43035 ... 60963 23326 53294]
55001.101866


In [32]:
info = np.random.randint(1000,600000,size=(1000000,2))
print(info)
np.savetxt("info.csv",info,delimiter=",")

[[563579 311073]
 [179516 456853]
 [ 45223 449345]
 ...
 [368700 198046]
 [341033 275558]
 [367997  41860]]


In [33]:
newinfo = np.genfromtxt("info.csv", delimiter=",")
print(newinfo)

[[563579. 311073.]
 [179516. 456853.]
 [ 45223. 449345.]
 ...
 [368700. 198046.]
 [341033. 275558.]
 [367997.  41860.]]


In [34]:
incomestandard = 450000
outcomestandard = 15000
euclidiandistance = []
for company in newinfo:
    incomedistance = math.pow((company[0] - incomestandard),2)
    outcomedistance = math.pow((company[1] - outcomestandard),2)
    euclidiandistance.append(incomedistance + outcomedistance)
numpyed = np.array(euclidiandistance)
#for index in numpyed:
    #print(index)

In [36]:
fivebest = np.argpartition(numpyed, 5)
print(fivebest)
print(numpyed[fivebest[:5]])

[ 41915  12003 918592 ...      4      2 499999]
[275600. 112996. 343625. 362765. 428740.]
